#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:
# Requirements:
# Accepts 4 parameters.
# The path to the file to be transferred.
# The IP of the server we want to transfer the file to.
# The username scp connects with.
# The path to the SSH private key that scp uses.
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed.
# scp must transfer the file to the user home directory ~/.
# Strict host key checking must be disabled when using scp.

argc=$#

if [ "$argc" -lt 3 ];
then
    echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else
    if [ "$argc" -eq 4 ];
    then
        scp -o StrictHostKeyChecking=no -i "$4" root@localhost: "$1" "$3@$2: ~/"
    elif [ "$argc" -eq 3 ];
    then
        scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
    fi
fi
