#!/usr/bin/env bash
# Script that install NGINX, be listening on port 80 and must return
# a page that contains the string "Holberton School"
# if the user try to acces /redirect_me should be redirect to random page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo sed -i "/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=OrK6QxS_ZRk permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
