#!/usr/bin/env bash
# Script that install NGINX, be listening on port 80 and must return
# a page that contains the string "Holberton School"
# if the user try to acces /redirect_me should be redirect to random page.
# if the user try to acces to not found page should be show "Ceci n'est pas une page"
# Customs headers. The name of the custom HTTP header must be X-Served-By.
# The value of the custom HTTP header must be the hostname of the server Nginx is running on.

# shellcheck disable=SC2154
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo sed -i "/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=OrK6QxS_ZRk permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404_error.html
sudo sed -i "/server_name _;/a error_page 404 /404_error.html;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
