#!/usr/bin/env bash
# Script that customs headers. The name of the custom HTTP header must be X-Served-By.
# The value of the custom HTTP header must be the hostname of the server Nginx is running on.

sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
