#!/usr/bin/env bash
#Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
command_=$(pgrep -f 'bash')
for i in $command_
do
    echo "$i bash"
done
