#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100.
#Requirements:
#   -Displays FizzBuzz when the number is a multiple of 3 and 5
#   -Displays Fizz when the number is multiple of 3
#   -Displays Buzz when the number is a multiple of 5
#   -Otherwise, displays the number
#   -In a list format
iter=1
while [ $iter -le 100 ]
do
    if [ $((iter % 15)) -eq 0 ]
    then
        echo FizzBuzz
    else
    if [ $((iter % 5)) -eq 0 ] 
    then
        echo Buzz
    else
    if [ $((iter % 3)) -eq 0 ]
    then
        echo Fizz
    else
        echo $iter
    fi
    fi
    fi
    ((iter++))
done
