#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
#   -displays bad luck for the 4th loop iteration.
#   -displays good luck for the 8th loop iteration.
#   -displays Holberton School for the other iterations.
iter=0
while [ $iter -lt 10 ]
do
    if [ $iter -eq 3 ]
    then
        echo bad luck
    elif [ $iter -eq 7 ]
    then
        echo good luck
    else
        echo Holberton School
    fi
    ((iter++))
done
