#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 (using while loop and case statement) and:
#   -displays 4 and then bad luck from China for the 4th loop iteration.
#   -displays 9 and then bad luck from Japan for the 9th loop iteration.
#   -displays 17 and then bad luck from Italy for the 17th loop iteration.
iter=0
while [ $iter -le 20 ]
do
    echo $iter
    case $iter in
        4)
            echo bad luck from China
        ;;
        9)
            echo bad luck from Japan
        ;;
        17)
            echo bad luck from Italy
        ;;
    esac
    ((iter++))
done      
