#!/usr/bin/env bash
#Bash script that displays:
#   -The content of the current directory.
#   -In a list format.
#   -Where only the part of the name after the first dash is displayed.
command_ls=$(ls)
for i in $command_ls
do
    echo "$i" | cut -d "-" -f2
done
