#!/usr/bin/env bash
#Bash script that gives you information about the holbertonschool file.
#Requirements:
#You must use if and, else (case is forbidden).
#Your Bash script should check if the file exists and print:
#   -if the file exists: holbertonschool file exists.
#   -if the file does not exist: holbertonschool file does not exist.
#If the file exists, print:
#   -if the file is empty: holbertonschool file is empty.
#   -if the file is not empty: holbertonschool file is not empty.
#   -if the file is a regular file: holbertonschool is a regular file.
#   -if the file is not a regular file: (nothing).
file="holbertonschool"
if [ -e ./$file ];
then
    echo "$file file exists"
    
    if [ -s ./$file ];
    then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi

    if [ -f ./$file ];
    then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
