#!/usr/bin/env bash
# Script that install ufw and setup: Block all incoming traffic except 22, 443 and 80 port.

sudo sudo apt-get install ufw
sudo ufw status
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw allow 8080/tcp # Alternative http 
sudo ufw enable
sudo ufw status verbose
