#!/usr/bin/env bash
#Bash script that configures an Ubuntu server. Modifies /etc/hosts file.
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
sed -i '$ a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
